# Generated by Django 6.0.5 on 2026-05-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'event categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.TextField()),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(max_length=500)),
                ('alt', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The Pause Project', max_length=120)),
                ('metadata_base_url', models.URLField(blank=True, default='https://thepauseproject.in', max_length=500)),
                ('default_meta_description', models.TextField(blank=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_cta_primary_label', models.CharField(blank=True, max_length=64)),
                ('hero_cta_primary_href', models.CharField(blank=True, max_length=200)),
                ('hero_cta_secondary_label', models.CharField(blank=True, max_length=64)),
                ('hero_cta_secondary_href', models.CharField(blank=True, max_length=200)),
                ('about_heading', models.CharField(blank=True, max_length=200)),
                ('about_body', models.TextField(blank=True)),
                ('about_sidebar_heading', models.CharField(blank=True, max_length=200)),
                ('about_sidebar_body', models.TextField(blank=True)),
                ('events_section_label', models.CharField(blank=True, max_length=64)),
                ('events_section_heading', models.CharField(blank=True, max_length=200)),
                ('events_section_body', models.TextField(blank=True)),
                ('gallery_section_label', models.CharField(blank=True, max_length=64)),
                ('gallery_section_heading', models.CharField(blank=True, max_length=200)),
                ('gallery_section_body', models.TextField(blank=True)),
                ('testimonials_section_label', models.CharField(blank=True, max_length=64)),
                ('testimonials_section_heading', models.CharField(blank=True, max_length=200)),
                ('contact_heading', models.CharField(blank=True, max_length=200)),
                ('contact_body', models.TextField(blank=True)),
                ('contact_address', models.TextField(blank=True)),
                ('contact_whatsapp_url', models.URLField(blank=True, max_length=500)),
                ('footer_tagline', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linktree', 'Linktree'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('href', models.URLField(max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date_display', models.CharField(max_length=64)),
                ('time_display', models.CharField(max_length=64)),
                ('venue', models.CharField(max_length=255)),
                ('price_display', models.CharField(max_length=32)),
                ('image', models.URLField(max_length=500)),
                ('booking_link', models.URLField(max_length=500)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cms.eventcategory')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cms.host')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('context', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='cms.workshopevent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms.workshopevent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
