# Generated by Django 5.2.14 on 2026-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_event_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopevent',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Session end time', null=True),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='event_date',
            field=models.DateField(help_text='Workshop calendar date'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='start_time',
            field=models.TimeField(help_text='Session start time'),
        ),
    ]
