# Generated by Django 5.2.14 on 2026-05-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_workshopevent_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryimage',
            name='image_url',
            field=models.ImageField(upload_to='event_gallery/'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(upload_to='hosts/'),
        ),
        migrations.AlterField(
            model_name='sitegalleryimage',
            name='src',
            field=models.ImageField(upload_to='site_gallery/'),
        ),
        migrations.AlterField(
            model_name='workshopevent',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
    ]
